# Based on https://github.com/teamspeak/teamspeak6-server/blob/9fa5ed86234e27ff969d9f95189e0b785358b520/compose/example-compose-sqlite.yaml
#
# If you want to use MariaDB edit this file accordingly, 
# using https://github.com/teamspeak/teamspeak6-server/blob/9fa5ed86234e27ff969d9f95189e0b785358b520/compose/example-compose-mariadb.yaml as a reference.

services:
  teamspeak:
    # image: teamspeaksystems/teamspeak6-server:latest # Make sure this is commented as the original image doesn't support ARM64
    container_name: teamspeak-server
    restart: unless-stopped
    # Make sure not to delete those 2 lines, and that this file is in the same folder as the Dockerfile and start.sh.
    # A pre-built DockerHub image may be provided in the future, depending how the beta test will evolve.
    build:
        dockerfile: ./Dockerfile
    ports:
      - "9987:9987/udp"    # Default voice port
      - "30033:30033/tcp"  # File transfer port
      # - "10022:10022/tcp" # (Optional) ServerQuery SSH port
      # - "10080:10080/tcp"  # (Optional) WebQuery port
    environment:
      - TSSERVER_LICENSE_ACCEPTED=accept
      - TSSERVER_DEFAULT_PORT=9987
      - TSSERVER_VOICE_IP=0.0.0.0
      - TSSERVER_FILE_TRANSFER_PORT=30033
      - TSSERVER_FILE_TRANSFER_IP=0.0.0.0
      # - TSSERVER_QUERY_HTTP_ENABLED=true
      # - TSSERVER_QUERY_SSH_ENABLED=false
      # - TSSERVER_MACHINE_ID=my_unique_machine_id
      # - TSSERVER_LOG_PATH=/var/tsserver/logs
      # - TSSERVER_QUERY_ADMIN_PASSWORD=secretpassword
    volumes:
      - tsserver-data:/var/tsserver

volumes:
  tsserver-data:
    name: tsserver-data
